name = "comfy-workflows-api"
main = "src/worker.ts"
compatibility_date = "2024-10-01"

kv_namespaces = [
  { binding = "WORKFLOWS", id = "07bdc4a0098649b9a7137901bfb24ccb" }
]

[vars]
CORS_ALLOW_ORIGIN = "*"
